#version 460
#extension GL_GOOGLE_include_directive : require

#define A_GPU 1
#define A_GLSL 1
#define FSR_RCAS_F 1

#include "ffx_a.h"
#include "ffx_fsr1.h"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D inputImage;
layout(set = 0, binding = 1, rgba8) uniform writeonly image2D outputImage;

layout(push_constant) uniform Push {
    uvec4 con;
} pc;

vec4 FsrRcasLoadF(ivec2 p) {
    ivec2 size = textureSize(inputImage, 0);
    return texelFetch(inputImage, clamp(p, ivec2(0), size - ivec2(1)), 0);
}

void FsrRcasInputF(inout float r, inout float g, inout float b) {}

void main() {
    uvec2 gid = gl_GlobalInvocationID.xy;
    if (any(greaterThanEqual(gid, uvec2(imageSize(outputImage))))) return;
    vec3 pix;
    FsrRcasF(pix.r, pix.g, pix.b, gid, pc.con);
    imageStore(outputImage, ivec2(gid), vec4(pix, 1.0));
}
