#ifndef OPEN_SCALING_FRAMEFLOW_PROTOCOL_H
#define OPEN_SCALING_FRAMEFLOW_PROTOCOL_H

#include <stdint.h>

#define FRAMEFLOW_MAGIC 0x4f464631u
#define FRAMEFLOW_VERSION 1u
#define FRAMEFLOW_RGB24 1u
#define FRAMEFLOW_HEADER_WORDS 10u
#define FRAMEFLOW_HEADER_SIZE (FRAMEFLOW_HEADER_WORDS * sizeof(uint32_t))
#define FRAMEFLOW_MAX_PIXELS (16u * 1024u * 1024u)
#define FRAMEFLOW_MIN_FACTOR 2u
#define FRAMEFLOW_MAX_FACTOR 4u

enum FrameFlowRequestField {
    FRAMEFLOW_REQ_MAGIC,
    FRAMEFLOW_REQ_VERSION,
    FRAMEFLOW_REQ_WIDTH,
    FRAMEFLOW_REQ_HEIGHT,
    FRAMEFLOW_REQ_FACTOR,
    FRAMEFLOW_REQ_FORMAT,
    FRAMEFLOW_REQ_FRAME_BYTES,
    FRAMEFLOW_REQ_SEQUENCE_HI,
    FRAMEFLOW_REQ_SEQUENCE_LO,
    FRAMEFLOW_REQ_RESERVED
};

enum FrameFlowResponseField {
    FRAMEFLOW_RES_MAGIC,
    FRAMEFLOW_RES_VERSION,
    FRAMEFLOW_RES_STATUS,
    FRAMEFLOW_RES_WIDTH,
    FRAMEFLOW_RES_HEIGHT,
    FRAMEFLOW_RES_FACTOR,
    FRAMEFLOW_RES_FRAME_BYTES,
    FRAMEFLOW_RES_SEQUENCE_HI,
    FRAMEFLOW_RES_SEQUENCE_LO,
    FRAMEFLOW_RES_RESERVED
};

enum FrameFlowStatus {
    FRAMEFLOW_STATUS_OK = 0,
    FRAMEFLOW_STATUS_BAD_REQUEST = 1,
    FRAMEFLOW_STATUS_INFERENCE_FAILED = 2
};

#endif
